### ISSUE TITLE
PR not automatically created by regro-cf-autotick-bot upon release on GitHub source repo

### ISSUE THREAD

**Issue by danielhuppmann** [conda-forge/pyam-feedstock#19]
Previously, a new PR was started by `regro-cf-autotick-bot` upon making a new release in the source repository https://github.com/IAMconsortium/pyam (as written in the [conda-forge docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#pushing-to-regro-cf-autotick-bot-branch)).

This is not happening with the latest [release 0.7.0](https://github.com/IAMconsortium/pyam/releases/tag/v0.7.0). Did something intentionally change or is this a bug?

Apologies if I missed an obvious section in the docs pages or issues...

**Comment by danielhuppmann** [comment]
@beckermr @conda-forge-admin you recently made changes to this feedstock - can you advise?

**Comment by beckermr** [comment]
I'm not sure. Can you file an issue at regro/cf-scripts? This is where we track bugs with the autotick bot.

**Comment by danielhuppmann** [comment]
Thanks for the redirect @beckermr, seems related to a similar issue already reported there...

Closing this issue here, bumped the version manually per #20.
