### ISSUE TITLE
Add argparse as requirement in next release

### ISSUE THREAD

**Issue by znicholls** [conda-forge/pyam-feedstock#34]
@danielhuppmann just as an fyi, argparse is in the `setup.py` but isn't listed as a requirement in `recipes/meta.yaml`, would be great to add it on the next release

**Comment by danielhuppmann** [comment]
Thanks for noticing - I guess that it's actually not needed anymore, will investigate...

**Comment by coroa** [comment]
It's not in `setup.cfg` anymore so closing.
