### ISSUE TITLE
Pint dependency

### ISSUE THREAD

**Issue by znicholls** [conda-forge/pyam-feedstock#39]
@danielhuppmann is it possible to cut a new release, the pint dependency in the 1.3.1 release needs to be updated. setup.cfg says pint < 0.17 (https://github.com/IAMconsortium/pyam/blob/v1.3.1/setup.cfg), the same pinning isn't applied here (https://github.com/conda-forge/pyam-feedstock/blob/main/recipe/meta.yaml)

**Comment by danielhuppmann** [comment]
Is it ok to wait for a few more days until https://github.com/IAMconsortium/pyam/pull/637 is merged?

**Comment by znicholls** [comment]
Depends when @jkikstra wants conda installs to work (I'm guessing not this week so probably fine to wait)

**Comment by jkikstra** [comment]
Yeah won't get to working on that part of the release process until next week
